= Intro to Java Class Notes
:source-highlighter: highlightjs

== The Main Method
The entry point to a program. Everything you want to happen in your program
should originate in the main method. myInterger = 5;
double myDouble = 10.0;
boolean myBoolean = false;
[source,java]
public static void main(String[] args) {

}

== Printing to the console

[source,java]
System.out.println("This will be printed.");

== Comments

Comments are notes developers make in their code. They do not change
what the code does.

[source,java]
// This is a comment.


== Variables

* Integer - A number without a decimal point.
* Double  - A number with a decimal point.
* Boolean - A variable that is either true or false.

[source,java]
int myInteger = 5;
double myDouble = 10.0;
boolean myBoolean = false;

== Operators

Relational Operators:

* ==	Equal
* !=	Not Equal
* <	Less than
* >	Greater than
* <=	Less than or Equal to
* >=	Greater than or Equal to

Conditional Operators:

* &&	And
* ||	Or

Precedence:
Relational operators are processed first, followed by conditional operators,
and then assignment (=).

In the following example,

[source,java]
boolean positiveNumbers = x > 0 && y > 0;

First the relational operators are processed (x > 0) and (y > 0).
Next, the conditional operator is processed (&&).
Finally, the assignment is done. (positiveNumbers = true).

== If Statements

With if statements you can execute different logic depending on the result
of the conditional.

[source,java]
int year = 2018;
if (year > 2000) {
  System.out.println("This is the 21st century.");
} else if (year > 1990) {
  System.out.println("It's the 90s");
} else {
  System.out.println("Other time period.")
}
